### ISSUE TITLE
Which version of ImageNet21K should I download

### ISSUE THREAD

**Issue by zhszysrh** [amazon-science/prompt-pretraining#10]
![image](https://github.com/amazon-science/prompt-pretraining/assets/107545756/b6dbd198-2c3b-4dd9-935e-e018f81b7e8d)
Which version of ImageNet21K should I download？The green one or the red one？Training prompt and Detic use the red one？The red one is about 280G，it that normal？

**Comment by RenShuhuai-Andy** [comment]
Hi, 
(1) yes, you should download the red one.
(2) yes, downloading ImageNet-21k requires huge disk space.

**Comment by zhszysrh** [comment]
I downloaded the red one, but MD5 didn't match, is that normal?
![image](https://github.com/amazon-science/prompt-pretraining/assets/107545756/488bdbcc-a273-44a6-8c91-9156e094e07a)
![image](https://github.com/amazon-science/prompt-pretraining/assets/107545756/a5b885ca-14b4-4713-b79a-8545f217c79d)

**Comment by RenShuhuai-Andy** [comment]
I don't think it is normal. It seems that you did not download the complete file. 
However, if you just want to reproduce the prompt pre-training experiment, I think it's ok to use the imperfect data, because our pre-training only samples up to 16 images for each class.

**Comment by zhszysrh** [comment]
I unzipped the red one, the directory structure like this, is that normal?
![image](https://github.com/amazon-science/prompt-pretraining/assets/107545756/610df801-6265-40b0-9334-9a3e6123d632)
![image](https://github.com/amazon-science/prompt-pretraining/assets/107545756/7b9f7b36-6c2c-46bf-9787-0e27c42dacac)

**Comment by RenShuhuai-Andy** [comment]
yes, you can refer to [https://github.com/amazon-science/prompt-pretraining/blob/main/docs/DATASETS.md#imagenet-21k](https://github.com/amazon-science/prompt-pretraining/blob/main/docs/DATASETS.md#imagenet-21k)

**Comment by zhszysrh** [comment]
I unzipped the red one, i got imagenet21k_small_classes directory, it only has 5592 folders, less than 8718
Is the two pick rectangles irrelevant to ImageNet21K?
Where are the two folders(imagenet21_train and imagenet21_val) in yellow rectangles come from? From the green one?
![image](https://github.com/amazon-science/prompt-pretraining/assets/107545756/2e4e5b1c-2dc5-4e9e-a333-626928fef7e6)
![image](https://github.com/amazon-science/prompt-pretraining/assets/107545756/12743a15-7ad3-4675-97b7-bda244839539)

**Comment by RenShuhuai-Andy** [comment]
Hi, I think you didn't completely download the datasets from the red one. As you said, imagenet21k_resized.tar.gz has 280.51 GB, if you download it completely, it should include 3 folders after decompression, i.e., `imagenet21k_train`, `imagenet21k_val`, `imagenet_21k_small_calsses`.

On my end, after decompression, the sizes are:
- imagenet21k_small_calsses: 33G
- imagenet21k_val: 12G 
- imagenet21k_small_calsses: 250G 

Please check the size of your imagenet_21k_small_calsses folder. If it's significantly less than 280G, that indicates the full archive was not downloaded.

**Comment by zhszysrh** [comment]
> Hi, I think you didn't completely download the datasets from the red one. As you said, imagenet21k_resized.tar.gz has 280.51 GB, if you download it completely, it should include 3 folders after decompression, i.e., `imagenet21k_train`, `imagenet21k_val`, `imagenet_21k_small_calsses`.
> 
> On my end, after decompression, the sizes are:
> 
> * imagenet21k_small_calsses: 33G
> * imagenet21k_val: 12G
> * imagenet21k_small_calsses: 250G
> 
> Please check the size of your imagenet_21k_small_calsses folder. If it's significantly less than 280G, that indicates the full archive was not downloaded.

Thank you for your reply. According to your reply, I have located a problem with the download process. After downloading it three times, I finally got the same decompression result as yours, and the md5 file is consistent with the official website
