### ISSUE TITLE
No checkpoints available under pretrained weights link

### ISSUE THREAD

**Issue by nhussein** [amazon-science/prompt-pretraining#3]
There are no pretrained weights available under the links posted in the section "Pre-trained POMP Prompt"

**Comment by RenShuhuai-Andy** [comment]
Hi, our ckpt of pretrained prompt is available in [here](https://github.com/amazon-science/prompt-pretraining/blob/main/docs/MODELS.md#pre-trained-pomp-prompt):

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/30052148/236197339-dd30c380-9f7b-4769-a52e-adc642455273.png">


The Google Drive link for all ckpts is [link](https://drive.google.com/drive/folders/1O3xUFK1qRFWN_n82T6qTn_G_-AHLIaWc?usp=share_link).

**Comment by jameelhassan** [comment]
Thank you for the reply with the google drive link for all the checkpoints. 
It seems that the google drive link for the ViT/B-16 models highlighted in your screenshot above does not seem to contain the checkpoints as it is only a few KBs.

**Comment by jameelhassan** [comment]
Thank you very much. Will try this.
