### ISSUE TITLE
Inference demo or  custom dataset inference script

### ISSUE THREAD

**Issue by BIGBALLON** [amazon-science/prompt-pretraining#5]
Thanks for your great work！ Is there any plan to release an Inference demo (single image or image folder) or interactive script(bash or  UI).

**Comment by RenShuhuai-Andy** [comment]
Hi, thanks for your interest. 

We have added an inference demo (for single image classification) in [Google Colab](https://colab.research.google.com/drive/1OEFw1GfKXogx8mdFS2pClLjPK3aPEZyY?usp=sharing). We hope this could be helpful.

For inference on your custom dataset, we recommend you to write `dataset prepare codes` like [food101.py](https://github.com/amazon-science/prompt-pretraining/blob/main/datasets/food101.py) and `dataset config file` like [food101.yaml](https://github.com/amazon-science/prompt-pretraining/blob/main/configs/datasets/food101.yaml), then import your dataset in [train.py](https://github.com/amazon-science/prompt-pretraining/blob/main/train.py). 
After that, you can eval on your custom dataset by using [eval.sh](https://github.com/amazon-science/prompt-pretraining/blob/main/scripts/pomp/eval.sh).

**Comment by BIGBALLON** [comment]
thanks a lot!

**Comment by zhszysrh** [comment]
> Hi, thanks for your interest.
> 
> We have added an inference demo (for single image classification) in [Google Colab](https://colab.research.google.com/drive/1OEFw1GfKXogx8mdFS2pClLjPK3aPEZyY?usp=sharing). We hope this could be helpful.
> 
> For inference on your custom dataset, we recommend you to write `dataset prepare codes` like [food101.py](https://github.com/amazon-science/prompt-pretraining/blob/main/datasets/food101.py) and `dataset config file` like [food101.yaml](https://github.com/amazon-science/prompt-pretraining/blob/main/configs/datasets/food101.yaml), then import your dataset in [train.py](https://github.com/amazon-science/prompt-pretraining/blob/main/train.py). After that, you can eval on your custom dataset by using [eval.sh](https://github.com/amazon-science/prompt-pretraining/blob/main/scripts/pomp/eval.sh).

 Is there any plan to release an Inference demo (for single image detection) or interactive script(bash or UI).
