### ISSUE TITLE
Inference demo for detection

### ISSUE THREAD

**Issue by zhszysrh** [amazon-science/prompt-pretraining#7]
Thanks for your great work！ Is there any plan to release an Inference demo (for single image detection) or interactive script(bash or UI).

**Comment by RenShuhuai-Andy** [comment]
Hi, thanks for your interest.

I have added an inference demo for object detection in [Jupyter file](https://github.com/RenShuhuai-Andy/prompt-pretraining/blob/main/third_party/Detic/demo/demo.ipynb). There are some new requirements for this demo, like the [pre-computed class features for LVIS](https://github.com/RenShuhuai-Andy/prompt-pretraining/blob/main/third_party/Detic/datasets/metadata/lvis_v1_clip_pomp%2Bcname.npy) (as well as [COCO](https://github.com/RenShuhuai-Andy/prompt-pretraining/blob/main/third_party/Detic/datasets/metadata/coco_clip_pomp%2Bcname.npy), [Object365](https://github.com/RenShuhuai-Andy/prompt-pretraining/blob/main/third_party/Detic/datasets/metadata/o365_fixname_clip_pomp%2Bcname.npy)) and the [environment.yaml](https://github.com/RenShuhuai-Andy/prompt-pretraining/blob/main/third_party/Detic/demo/environment.yaml). 

You can follow [my own repo](https://github.com/RenShuhuai-Andy/prompt-pretraining/tree/main) for the latest change. @astonzhang will merge my new PRs at his convenience. 

We hope this could be helpful.

**Comment by zhszysrh** [comment]
very helpful, thanks again
