### ISSUE TITLE
ImageNet-21K's classnames.txt is the same as ImageNet-1K's classnames.txt

### ISSUE THREAD

**Issue by zhszysrh** [amazon-science/prompt-pretraining#8]
I download ImageNet-21K's classnames.txt from the link 
![ImageNet-21K](https://github.com/amazon-science/prompt-pretraining/assets/107545756/e2adeb57-8bf3-4e4e-8986-368e965285dc)

it only has 1000 rows and it is the same as  ImageNet-1K's classnames.txt which is from the link 
![ImageNet-1K](https://github.com/amazon-science/prompt-pretraining/assets/107545756/eec381c9-a659-421f-a0c7-d71278fa4323)

I thought there should be more than 21K lines in ImageNet-21K's classnames.txt, am i right?

**Comment by RenShuhuai-Andy** [comment]
Oh, my bad. You don't need to download classnames.txt for ImageNet-21K. 
Just download `imagenet21k_miil_tree.pth`, which contains all the classnames for ImageNet-21K, see [here](https://github.com/amazon-science/prompt-pretraining/blob/main/datasets/imagenet_21k.py#L24-L32).

**Comment by zhszysrh** [comment]
> Oh, my bad. You don't need to download classnames.txt for ImageNet-21K. Just download `imagenet21k_miil_tree.pth`, which contains all the classnames for ImageNet-21K, see [here](https://github.com/amazon-science/prompt-pretraining/blob/main/datasets/imagenet_21k.py#L24-L32).

OK. Thank you for your quick response
