### ISSUE TITLE
Cannot get Object365 classname

### ISSUE THREAD

**Issue by zhszysrh** [amazon-science/prompt-pretraining#9]
`
from detectron2.data import MetadataCatalog, DatasetCatalog

BUILDIN_METADATA_PATH = {
    'lvis': 'lvis_v1_val',
    'objects365': 'objects365_v2_val',
    'coco': 'coco_2017_val',
}
vocabulary = 'objects365' # change to 'lvis', 'objects365', 'openimages', or 'coco'
metadata = MetadataCatalog.get(BUILDIN_METADATA_PATH['objects365'])
num_classes = len(metadata.thing_classes)`

![image](https://github.com/amazon-science/prompt-pretraining/assets/107545756/61be6d94-a580-4a4a-83d6-87ab79927811)

**Comment by zhszysrh** [comment]
And i cannot find the 【zhiyuan_objv2_val.json】 download link in https://data.baai.ac.cn/details/Objects365_2020
![image](https://github.com/amazon-science/prompt-pretraining/assets/107545756/5df0d209-82d0-4930-b469-8ad9c3d6a743)

**Comment by RenShuhuai-Andy** [comment]
It seems that `zhiyuan_objv2_val.json` is lost after the official website is updated, you can download it from [https://github.com/RenShuhuai-Andy/prompt-pretraining/releases/download/v1.0/zhiyuan_objv2_val.json](https://github.com/RenShuhuai-Andy/prompt-pretraining/releases/download/v1.0/zhiyuan_objv2_val.json).

**Comment by zhszysrh** [comment]
It's helpful. Thank you for your quick response.
